name: Run Bragg Neural Network Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Cambia la versión si es necesario

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas tensorflow keras keras-tuner scikit-learn matplotlib seaborn

    - name: Run analysis script
      run: |
        python redNeuronalv5.py  # Asegúrate de que el archivo esté en el directorio raíz del repositorio